### ISSUE TITLE
Easily adapted to Kegg Pathways?

### ISSUE THREAD

**Issue by phillipeloher** [tanghaibao/goatools#103]
I got this working with go-basic.obo.  Are there similar databases in the format that Goatools requires that would allow this tool to find enrichments in Kegg Pathways?  Would like to use the same tool (not DaviD, enrichR, or other remote calling tools) if possible.  Thanks!

**Comment by dvklopfenstein** [comment]
Thank you for your interest in GOATOOLS and taking the time to write us.

I too have wanted the functionality that you are requesting for my own research. Unfortunately, we have not had the time to implement this. We have an architecture in mind that would  be extensible to other data sets, not just Kegg Pathways. But right now, all the time has been consumed with creating code to facilitate semi-automated GO grouping . We have a paper that is close to completion that describes the new grouping functionality, which will be released close to publication.

Thank you for expressing interest in this important functionality. We do have plans, but right now it is not feasible time-wise. We will put this higher on the list due to user interest.

Thank you again  for your interest in GOATOOLS and expressing interest in this useful new functionality.

**Comment by phillipeloher** [comment]
Thanks so much for the fast reply!  Also looking forward to looking at your upcoming paper.  Very happy about this open source project.  With regards to Kegg and other Pathway enrichment, there are databases such as msigdb that could be helpful.  The reason I'm not currently using GSEA is because it appears to require rankings or expression, doesn't have good/supported local APIs (has a bulky Java tool UI, etc.) to call within Python/R, etc.

**Comment by dvklopfenstein** [comment]
Thank you for your interest in GOATOOLS and taking the time to write us to express your priorities. I am going to close this issue. It you believe that the issue has not been satisfactorily resolved, please open a new issue.

But no, unfortunately, the code is not easily extensible to databases, other than GO.
