### ISSUE TITLE
loading gaf

### ISSUE THREAD

**Issue by mirauta** [tanghaibao/goatools#105]
I'm trying to use a different gene2go association file and to load the goa_human.gaf. The following error occurs: AssertionError: UNEXPECTED QUALIFIER(CONTRIBUTES_TO).

**Comment by dvklopfenstein** [comment]
Thank you for your interest in GOATOOLS and thank you for taking the time to write to us.

That should be an old error which a newer version of GOATOOLS has fixed. The issue was some gaf files some times would have different Did you install GOATOOLS using pip or by forking/cloning.

Also, just to be sure, can you email your gene2go association file and the goa_human.gaf file that you are using? My email is my username with a gmail ending and can be found on my GitHub homepage.

**Comment by dvklopfenstein** [comment]
Thank you for taking the time to write us regarding the issue you are seeing.

Using the latest GOATOOLS version should address your issue. I am going to close this issue because the latest versions should address the issue. If this is not the case, please re-open a new issue. 

Thank you again for your time and interest.
