### ISSUE TITLE
print_summary : not behaving as expected

### ISSUE THREAD

**Issue by cross12tamu** [tanghaibao/goatools#112]
print_summary is currently not running as expected. Version number = v0.8.9.

Here is the "set-up" for running the print_summary, and getting the GOEnrichmentStudy obj

```
ecoli_keys = GAF_ecoli.keys()
study = tca_dict.keys()
methods = ['fdr']

g = GOEnrichmentStudy(ecoli_keys, matches_reference, obodag,
                      propagate_counts = True, alpha = 0.05,
                      methods = methods)

g_res = g.run_study(study)
g_sig = [r for r in g_res if r.p_fdr < 0.05]
```

Below are the output results for print_summary(g_sig)
```
# min_ratio=[GOEnrichmentRecord(GO:0006101), GOEnrichmentRecord(GO:0006099), GOEnrichmentRecord(GO:0006091), GOEnrichmentRecord(GO:0072350), GOEnrichmentRecord(GO:0017144), GOEnrichmentRecord(GO:0045333), GOEnrichmentRecord(GO:0015980), GOEnrichmentRecord(GO:0016999), GOEnrichmentRecord(GO:0009060), GOEnrichmentRecord(GO:0019752), GOEnrichmentRecord(GO:0043436), GOEnrichmentRecord(GO:0044237), GOEnrichmentRecord(GO:0006082), GOEnrichmentRecord(GO:0055114), GOEnrichmentRecord(GO:0008152), GOEnrichmentRecord(GO:0045239), GOEnrichmentRecord(GO:0009361), GOEnrichmentRecord(GO:0042709), GOEnrichmentRecord(GO:0016836), GOEnrichmentRecord(GO:0016835), GOEnrichmentRecord(GO:0004333), GOEnrichmentRecord(GO:0048037), GOEnrichmentRecord(GO:0051539), GOEnrichmentRecord(GO:0003824), GOEnrichmentRecord(GO:0016829), GOEnrichmentRecord(GO:0051536), GOEnrichmentRecord(GO:0003994), GOEnrichmentRecord(GO:0051540), GOEnrichmentRecord(GO:0003730), GOEnrichmentRecord(GO:0009055), GOEnrichmentRecord(GO:0000104)] pval=0.05
```

As mentioned in my other tracker item, the print_results works (it didn't in the previous version), and the print_summary worked as expected in that previous version. NOW, the print_summary prints this instead. 

 And of course, let me know if you need anything else from me.

Thanks in advance,
Curtis

**Comment by dvklopfenstein** [comment]
Hello cross12tamu,

Thank you so much for taking the time to write to us and for your interest in GOATOOLS.

The function, _print_summary_, has a first argument, _min_ratio_, (not _goea_results_) which is supposed to be data of type float. I think this function is named misleadingly and a more accurate function name should be _print_date()_ because the function's purpose is to print the GOATOOLS version and the date the GOEA was run.

The name print_summary() does incorrectly lead one to believe that you will get a summary of your GOEA results. I will change the name to prevent confusion in the future. The first argument of print_summary should be _min_ratio_, not _goea_results_.

The _min_ratio_ argument is used to limit the GOEA results shown to those where the ratio of study genes associated with a GO term and the ratio of population genes associated with the same GO term is different and is bigger than the threshold that you set using _min_ratio_.

The _min_ratio_ runtime argument is useful for not reporting significant GO terms associated with large numbers of genes if the study gene ratio and the population gene ratio and are similar.

I am going to close this issue, but I will be changing the function name in the code to more accurately describe its true function (printing the date and GOATOOLS version).

Thank you very much for using GOATOOLS.
