### ISSUE TITLE
Enriched GOs are not listed in the association file 

### ISSUE THREAD

**Issue by Arash-Iranzadeh** [tanghaibao/goatools#128]
Hi,
I ran this command:
$find_enrichment.py study population association  --pval=0.05 --pval_field=fdr_bh  --outfile=results.tsv

The ratios in the result files do not match with the association file, for example consider this GO in the result.tsv:
GO     ratio_in_study     ratio_in_pop
GO:0036211     33/276     1725/33239

It mentions this GO happens 1725 times in the population, but when I search it in the association file, it is not there! Why?

Thanks!

**Comment by tanghaibao** [comment]
@Arash-Iranzadeh 

This is what we say in the tutorial:

> **Important note**: by default, `find_enrichment.py` propagates counts to all the parents of a GO term. As a result, users may find terms in the output that are not present in their association file. Use `--no_propagate_counts` to disable this behavior.

GO:0036211 is a high level GO term so that's why many genes point to its descendants (protein kinases, etc.) even if they are not annotated as the term per se.

**Comment by dvklopfenstein** [comment]
@Arash-Iranzadeh,

Thank you so much for your interest in GOATOOLS and taking the time to write us. 

Yes, as @tanghaibao describes, we have propagate_counts on by default because our simulations and investigations in the results of other enrichment tools showed that propagate_counts greatly helps improve the sensitivity as shown in this figure from our paper. The top panel shows propagate counts as False. The bottom shows True.

![fig3_genes](https://user-images.githubusercontent.com/7278188/58129373-980a8980-7be7-11e9-9355-a9fde6935548.png)

Please give it a try with propagate_counts set to False. 

I will close this Issue. But if there are any questions or comments upon trying --no_propagate_counts, please open new issue.

Thank you again so much for taking the time to contact us.
