### ISSUE TITLE
Enhancement: Add kws for quiet printing throughout the library

### ISSUE THREAD

**Issue by SirSharpest** [tanghaibao/goatools#133]
Hi, 

Minor issue, if encorperating goatools into other pipelines it can get quite messy with the large volumes of printing. I propose a key-word argument to disable them. 

For example insertion of one line (and 1 indent) would be sufficient at each command which outputs: [forked example of 1 particularly verbose output](https://github.com/SirSharpest/goatools/blob/master/goatools/go_enrichment.py#L294)

if this is something which would be considered I can properly implement and make a pull request.

**Comment by dvklopfenstein** [comment]
Having a quiet option is a terrific idea!

Please do implement the code, if you are comfortable doing so. Before doing the pull request, please be sure that all the files that you edited pass pylint on the lines that you edited and run all the tests using:

```
$ make pytest
```

Thank you for your interest in GOATOOLS, for taking the time to write us, and for tacking the task of adding this code.

**Comment by dvklopfenstein** [comment]
This is a fantastic idea. I don't currently have time to modify the code in all places, but will attack it piece by piece as it comes up with current tests and functionality. Thank you so much for the great idea. If you have any further feedback, please fell free to leave specific details.

**Comment by BenjaSanchez** [comment]
Just wanted to support this issue: I'm using `run_study` in a jupyter notebook within a Github repo, and it's virtually impossible to track changes with so much output. Also some lines of the output keep changing in format like in [here](https://github.com/computer-aided-biotech/phenobooth-analysis/commit/8d6fb1c73577ab82b2793f2fca58c8d9139026c5#diff-1df2bfb5f4c9eddf3ba1e1862f1112c4L1687), not sure if that is an intended behavior.

In the meantime I switched to the forked version of @SirSharpest and after adding an additional commit to enable `**kvargs` in `run_study` within the `GOEnrichmentStudyNS` object (see [my fork](https://github.com/BenjaSanchez/goatools/commit/38abb784dcc3b6d6094b68737a55644b5e3cd55c)) works like a charm, thank you!

**Comment by dvklopfenstein** [comment]
@BenjaSanchez,

Thank you so much for your interest in GOATOOLS and taking the time to write us to vote for expanding quiet mode to the `run_goea` function.

By default, we are verbose to prevent missing anything, but we wholeheartedly support quiet modes to be run upon user request.

I have added quiet mode to the `run_goea` function and added a new section, **5a. Quietly Run a GOEA**, to the [**Jupyter notebook**](https://github.com/tanghaibao/goatools/blob/master/notebooks/goea_nbt3102.ipynb) which shows that `run_goea` can be run quietly by adding the `prt=None` argument as follows:
```
run_study(geneids_study, prt=None)
```
rather than:
```
run_study(geneids_study)
```
See the Jupyter notebook for the full example. But for more context:
```
# Run a Gene Ontology Enrichment Analysis
goeaobj = GOEnrichmentStudyNS( ..., methods=['fdr_bh'])
goea_quiet_all = goeaobj.run_study(geneids_study, prt=None)

# Extract the significant GOEA results
goea_quiet_sig = [r for r in goea_results_all if r.p_fdr_bh < 0.05]
```

Since the `run_goea` is so quiet, I have also added examples in the [**Jupyter notebook**](https://github.com/tanghaibao/goatools/blob/master/notebooks/goea_nbt3102.ipynb) under the **5a** section in **Print customized results summaries** so that researchers can choose to print their own more succinct GOEA summary.

@tanghaibao, can you release a new version of GOATOOLS once the regression tests have passed? Many people have been asking for this, so it would be helpful to release it ASAP.

**Comment by tanghaibao** [comment]
@dvklopfenstein 

Updated to `v1.0.3` and released on PyPI.

**Comment by BenjaSanchez** [comment]
@dvklopfenstein `prt=None` works perfectly, thanks for adding the feature! My notebooks appreciate it a lot :)
