### ISSUE TITLE
Calculating Lin's Similarity if a gene in the pair is not annotated

### ISSUE THREAD

**Issue by serbulent** [tanghaibao/goatools#148]
When the Lin similarity is calculated there are values over 1. Also some of the similarities for the same term pairs calculated as 0. I'm attaching a screen shot of some sample terms.

![GOA_tools_lin_similarity_problem_1](https://user-images.githubusercontent.com/765404/72216179-d7973480-352e-11ea-999b-a35aa2c35739.png)

**Comment by dvklopfenstein** [comment]
Thank you for opening this issue. I will take a look at this shortly.

**Comment by serbulent** [comment]
Thanks,

I think for the 0 calculation problem the order of the if controls needed to be changed in the function as below;

def lin_sim_calc(goid1, goid2, sim_r, termcnts):
    '''
        Computes Lin's similarity measure using pre-calculated Resnik's similarities.
    '''
    if sim_r is not None:
        info = get_info_content(goid1, termcnts) + get_info_content(goid2, termcnts)
        if sim_r == 0:
            return 1.0 if goid1 == goid2 else 0.0
        if info != 0:
            return (2*sim_r)/info
    return None

**Comment by dvklopfenstein** [comment]
Thank you. I am using this code in my PhD thesis, and have it fixed in beta repo, but need to move the fix over to the GOATOOLs production code. I am just wrapping up a manuscript now, so can look at it starting Thursday.

**Comment by dvklopfenstein** [comment]
Thank you for opening this issue. I am taking a look at it now. Which association file did you use?

**Comment by dvklopfenstein** [comment]
Lin similarity scores were showing up as greater than 1.0 if one or both of the GOs in the pair are not annotated. In the example you provided, GO:0101002 (boxed in red), is not annotated.

GO terms that are not annotated show an information score of 0.0, seen as the red boxed "i0.0" in the figure.

![i148_semsim_lin](https://user-images.githubusercontent.com/7278188/73140177-ed831a00-4043-11ea-938c-0f74e49493c7.png)

I am changing the code so:
1) Any GO ID compared with itself gets a Lin similarity score of 1.0

If one or both of the GO terms in the pair is not annotated:
1) If the GO pair's Most Important Common Ancestor (MICA) is the root term, in this case GO:0005575 *cellular_component*, the Lin score will be 0.0 since the resnick score is 0.0
2) Otherwise, the Lin score will be None (see bottom row and rightmost column):

GO IDs    |GO:0005766|GO:0008021|GO:0016591|GO:0042581|GO:0042582|GO:0070820|GO:0101002|
----------|----------|----------|----------|----------|----------|----------|----------|
GO:0005766|  1.000000|  0.103218|  0.000000|  0.087335|  1.000000|  0.080898|      None|
GO:0008021|  0.103218|  1.000000|  0.000000|  0.638649|  0.625280|  0.582680|      None|
GO:0016591|  0.000000|  0.000000|  1.000000|  0.000000|  0.000000|  0.000000|  0.000000|
GO:0042581|  0.087335|  0.638649|  0.000000|  1.000000|  0.582551|  0.548614|      None|
GO:0042582|  1.000000|  0.625280|  0.000000|  0.582551|  1.000000|  0.539613|      None|
GO:0070820|  0.080898|  0.582680|  0.000000|  0.548614|  0.539613|  1.000000|      None|
GO:0101002|      None|      None|  0.000000|      None|      None|      None|  1.000000|


The "None" Lin score can be overridden. In this example, we replace `None` with `-1.0`:

```
from goatools.semantic import lin_sim
val = lin_sim('GO:0101002', 'GO:0005766', godag, tcntobj, dfltval=-1.0 )
```

GO IDs    |GO:0005766|GO:0008021|GO:0016591|GO:0042581|GO:0042582|GO:0070820|GO:0101002|
----------|----------|----------|----------|----------|----------|----------|----------|
GO:0005766|  1.000000|  0.103218|  0.000000|  0.087335|  1.000000|  0.080898| -1.000000|
GO:0008021|  0.103218|  1.000000|  0.000000|  0.638649|  0.625280|  0.582680| -1.000000|
GO:0016591|  0.000000|  0.000000|  1.000000|  0.000000|  0.000000|  0.000000|  0.000000|
GO:0042581|  0.087335|  0.638649|  0.000000|  1.000000|  0.582551|  0.548614| -1.000000|
GO:0042582|  1.000000|  0.625280|  0.000000|  0.582551|  1.000000|  0.539613| -1.000000|
GO:0070820|  0.080898|  0.582680|  0.000000|  0.548614|  0.539613|  1.000000| -1.000000|
GO:0101002| -1.000000| -1.000000|  0.000000| -1.000000| -1.000000| -1.000000|  1.000000|

**Comment by serbulent** [comment]
Thanks for your attention. Your approach will solve the problem but might be a bit conservative. Instead you might choose to regularize the calculation method by assigning 1 annotation to each term as default. In that case a similarity score can be calculated for all terms.

**Comment by dvklopfenstein** [comment]
Hello @serbulent , Having an option to assigning a small value to user-requested unannotated GO terms is a great idea. This will not be the default, but will be available as an easily accessible option.

I will give the implementation some thought and then apply it. Please add any comments, if desired.

Thank you so much for opening this issue, for your interest in GOATOOLS, and for your good ideas.
