### ISSUE TITLE
wr_hier.py only return GOterms in namespace 'BP'

### ISSUE THREAD

**Issue by NewTearingHeaven** [tanghaibao/goatools#163]
Dear author, i was running
$ scripts/wr_hier.py BP MF CC --gene2go=gene2go --taxid=9606 --dash_len=17 --concise -o human_BP_MF_CC.txt
but the results in txt only includes those GOterms in 'BP'. I've checked the gene2go file and it does include MF and CC.
Full results are here:
  EXISTS: go-basic.obo
go-basic.obo: fmt(1.2) rel(2020-03-23) 47,232 GO Terms
HMS:0:00:04.080605 330,518 annotations, 20,562 genes, 18,403 GOs, 1 taxids READ: gene2go 
18499 IDs in loaded association branch, BP
NoneGoSubDag: 47232 sources in 47232 GOs rcnt(True). 2701 alt GO IDs
NoneGoSubDag: namedtuple fields: NS level depth GO alt GO_name dcnt D1 tcnt tfreq tinfo id
NoneGoSubDag: relationships: set()
NoneGoSubDag: 12378 sources in 15696 GOs rcnt(True). 0 alt GO IDs
NoneGoSubDag: namedtuple fields: NS level depth GO alt GO_name dcnt D1 id
NoneGoSubDag: relationships: set()
  WROTE: human_BP_MF_CC_test.txt

**Comment by dvklopfenstein** [comment]
Thanks for reporting this and thank your for the specific command to replicate the issue.

You are correct. We changed the underlying infrastructure of the annotation readers so that they all share a common base class and in addressing another issue to separate the GO terms more easily into BP, MF, and CC, this command wrongly no longer prints MF and CC.

I'll fix this shortly. Not catching this earlier was due to missing functionality in the tests, which will also be corrected.

Thank so much for being alert and for taking the time to report this issue. And thank you for your interest in GOATOOLS.

**Comment by dvklopfenstein** [comment]
@tanghaibao , Can you please create a new version? This is an important fix and should be available to all. Thanks.

**Comment by NewTearingHeaven** [comment]
Thanks for your reply

**Comment by tanghaibao** [comment]
@dvklopfenstein @NewTearingHeaven 

Updated the PyPi version to [v1.0.5](https://pypi.org/project/goatools/1.0.5/).

**Comment by NewTearingHeaven** [comment]
thanks for your reply



---Original---
