### ISSUE TITLE
Cannot read supplemental table 4

### ISSUE THREAD

**Issue by IrinnaP** [tanghaibao/goatools#164]
Supp table 4 of the Nature paper only has two columns (no info on directionality/fold change?) and when I try to read it as per the notebook I get this error: not enough values to unpack (expected 3, got 2). Any ideas? Thank you

**Comment by liangy1990** [comment]
Hi, that part I tried with this:

for r in range(pg.nrows):

        geneid, symbol = [pg.cell_value(r, c) for c in range(pg.ncols)]

I loaded my sheet instead of table 4, and my first column is gene ID, second column is Gene Symbol. You can set this regarding to your excel sheet format. If you have three column, for example a,b,c just write a,b,c = [pg.cell_value(r, c) for c in range(pg.ncols)]

Hope this helps!
