### ISSUE TITLE
Pronunciation (not a REAL issue)

### ISSUE THREAD

**Issue by cross12tamu** [tanghaibao/goatools#173]
I have been at (online) BCC2020 conference the past few days and ran into someone doing a GO (CrowdGO @mjmfreijnders) analysis. I discussed that I had used GOATOOLS before in my own analysis with GO.

I realized that I hadn't ever said this tool "out loud", other than with those that I have worked closely with on the project where I utilized this tool.

I (quite embarrassingly) pronounced it for the past year-plus "GOAT-TOOLS". I don't know why, but it's what myself and collabs have called it in our meetings, etc. I realize when I was talking to @mjmfreijnders he didn't know what I was talking about until we clarified some more. He pronounced the tool, "GO-UH-TOOLS". This... makes more sense. I'm curious if this is also how y'all pronounce the tool? Naturally, I was (and am) was a bit embarrassed by this mistake 😅. 

This is not a serious issue (obviously). I am just curious. Hopefully, when I evangelize for GOATOOLS next time, I say it correctly in the future 😄

**Comment by dvklopfenstein** [comment]
Thank you for your interest in GOATOOLS and for taking your time to write us.

Yes, the pronunciation is not clearly stated on in the README.

We say, "Go-Uh-Tools." 

Perhaps we should have named the tool using capitalization, **GoaTools**, rather than **GOATOOLS**. Your story is not the first story of different pronunciations.

Thank you so much for you support and interest. Surely, many users have thought the same thing.  Thank you for the humorous issue.

**Comment by cross12tamu** [comment]
Good to know! 👍
