### ISSUE TITLE
maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by z2e2** [tanghaibao/goatools#177]
Hi I am trying to use goatools to find ancestors of a GO term by the following code:
```
from goatools.base import get_godag
godag = get_godag('go.obo', optional_attrs='relationship')

GO_ID = 'GO:0050807'

from goatools.gosubdag.gosubdag import GoSubDag

gosubdag_r0 = GoSubDag([GO_ID], godag, prt=None)
print('{GO} ancestors: {P}'.format(
    GO=GO_ID,
    P=gosubdag_r0.rcntobj.go2parents[GO_ID]))
```
But I got an `RecursionError: maximum recursion depth exceeded while calling a Python object` error. I think there might be wrong when parsing the go.obo file. Would you please help me fix this problem?

**Comment by dvklopfenstein** [comment]
Thank you so much for your interest in GOATOOLS and thank you for taking your time to report a recursive error and thank you especially for extremely clear code showing how you came upon the issue.

I have implemented your code in a new test and am not seeing a recursion error in that test at this time. Can you upgrade your GOATOOLS version to the latest version and try it again?

Also, please note that the `go2parents` is deprecated and will be replaced by `go2ancestors` since `parents` refers to the immediate predecessors and `ancestors` refers to all predecessors.

**Comment by z2e2** [comment]
Thanks for your updates, it answered my problem.
