### ISSUE TITLE
Support for Ensembl IDs

### ISSUE THREAD

**Issue by detrout** [tanghaibao/goatools#200]
Hi,

I was trying to use goatools with Ensembl IDs and managed to manipulate biomart results into a gene2go like format.

Unfortunately goatools requires that geneid is an integer. would it be possible to relax that assumption?

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/goatools/anno/init/reader_genetogo.py", line 79, in init_associations
    geneid = int(vals[1])
ValueError: invalid literal for int() with base 10: 'ENSMUSG00000064370.1'

  **FATAL: invalid literal for int() with base 10: 'ENSMUSG00000064370.1'

**FATAL: ensembl_gene2go[2]:
10090	ENSMUSG00000064370.1	GO:0022904	IEA	-	respiratory electron transport chain	-	Process
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

2
 0) tax_id        10090
 1) DB_ID         ENSMUSG00000064370.1
 2) GO_ID         GO:0022904
 3) Evidence_Code IEA
 4) Qualifier     -
 5) GO_term       respiratory electron transport chain
 6) DB_Reference  -
 7) NS            Process

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/goatools/anno/init/reader_genetogo.py", line 79, in init_associations
    geneid = int(vals[1])
ValueError: invalid literal for int() with base 10: 'ENSMUSG00000064370.1'
```

**Comment by dvklopfenstein** [comment]
Thank you so much for your interest in GOATOOLS.

Would it be possible to convert the biomart results into a [gaf format](http://geneontology.org/docs/go-annotation-file-gaf-format-2.1/) rather than NCBI's gene2go format?

This should work very well with Ensemble IDs.

There are 17 fields in the GAF format. However, for fields that you are not using you could just use an empty string.

What does the biomart format look like? Perhaps I could add a biomart-to-gaf  script to GOATOOLS.

Thank you so much for taking your time to write us.

**Comment by detrout** [comment]
I wasn't sure how to get goatools to load other formats from the example notebook I was looking at.

At http://useast.ensembl.org/biomart/ I was able to select ensembl gene ids and plausible looking GO terms and got them back in a order, though since it's dynamic it depends on which fields you select. Also I can't figure out if they have anything like the Qualifier field.

I worked around the problem by subclassing InitAssoc and Gene2GoReader
