### ISSUE TITLE
Installation or PATH issue

### ISSUE THREAD

**Issue by johnacurtin** [tanghaibao/goatools#203]
Hi, 
I have installed goatools as per "https://github.com/tanghaibao/goatools".
When I started running your example notebook: "Run a Gene Ontology Enrichment Analysis (GOEA)" I could load the ontologies with no issues, however when I try to Load the Associations I get the following errors

    from goatools.anno.genetogo_reader import Gene2GoReader
ImportError: No module named genetogo_reader

    from genes_ncbi_10090_proteincoding import GENEID2NT as GeneID2nt_mus
ImportError: No module named genes_ncbi_10090_proteincoding

As well as doing a conda install I also cloned your git and I can see genetogo_reader.py in goatools/anno/
and genes_NCBI_10090_ProteinCoding.py in goatools/test_data/

Do I need to set a PATH to a location in your cloned git, or should the conda install have have installed these modules? 
thanks

**Comment by dvklopfenstein** [comment]
Thank you for  your interest in GOA TOOLs. And thank you for taking the time to write.

It sounds like you might have an old version of GOA TOOLs.

Do this to get the version:

```
python -c "import goatools; print(goatools.__version__)"
```

**Comment by johnacurtin** [comment]
Hi, 
Thanks for that. its v1.0.15

**Comment by dvklopfenstein** [comment]
That version of GOA TOOLs sounds correct. Conda should have installed the Gene2GoReader module. Please check this with:

```
$ python -c "from goatools.anno.genetogo_reader import Gene2GoReader; print(Gene2GoReader)"
<class 'goatools.anno.genetogo_reader.Gene2GoReader'>
```

Please let us know if that works. 

The mouse genes module was removed because people were using the protein coding genes for mouse (genes_ncbi_10090_proteincoding ) in for their day-to-day work.  That file was intended to be an example only and not for current work, so it was removed to prevent confusion. This notebook example will need to be updated. I have a deadline of next Friday for a different project, so will need to look at this issue after that deadline. At that time, I will re-run all the notebook examples to ensure that they are up to date.

**Comment by johnacurtin** [comment]
Hi, 
When I do as you suggested I get class 'goatools.anno.genetogo_reader.Gene2GoReader'
Thanks
