### ISSUE TITLE
GOEA as in the jupyter notebook with my own files

### ISSUE THREAD

**Issue by ziphra** [tanghaibao/goatools#205]
Hello, 

I would like to know how could I run a gene ontology enrichment analysis with my own files using a python IDE following your example from the Jupiter notebook (without downloading associations or background gene sets from NCBI, as in the example). I am not sure I get all the requirements to do so. 

Thank you!

**Comment by tanghaibao** [comment]
@ziphra 

Sorry for a late response ... not sure if you are still stuck on this one but the Jupyter notebook is no different from a Python IDE. There is no magic to download separate files and `goatools` automates some of the downloading as well. 

Would you point to which notebook that you are interested in running in a Python IDE but couldn't run due to missing datasets?

**Comment by rivera-galo** [comment]
I replied to another issue that might be similar 

https://github.com/tanghaibao/goatools/issues/113#issuecomment-880779873

I hope this helps.
