### ISSUE TITLE
a couple of  small issues with the readme

### ISSUE THREAD

**Issue by yotamcons** [tanghaibao/goatools#235]
Hey there,
first of all - thank you for your tool :)

two small things in the README:
1. a typo states GEOA instead of GOAE (line 75)
2. The wget link to the current obo file redirects to http://current.geneontology.org/ontology/go-basic.obo (added "current.") for wget users it is not a problem (wget allows redirections) but mac user like me who use "curl" need the exact address, or we just get the http "found" response.
3. the link to the GO slim obo suffers the same issue 
4. In the installation section, it would be beneficial to explicitly write the conda installation command: `conda install -c bioconda goatools`
5. For the dependencies section, the first line shouldn't be bulleted, and a short explanation should state "when installing through pip of bioconda, the below listed dependencies are downloaded"

Thank you again :)

**Comment by dvklopfenstein** [comment]
Thank you so much for your interest and the great, detailed feedback.

I would be extremely happy to implement your suggestions. This is a terrific issue.

If you would rather make the changes and issue a pull request, we would love to accept it.

Thank you again.

**Comment by yotamcons** [comment]
Would love to, only I haven’t done it before. is there a simple guide somewhere/could you DM me with instructions? 

yours,

Yotam

**Comment by dvklopfenstein** [comment]
We are excited and honored that you would like to do your first pull request with GOA TOOLs. Thank you so much for your time and interest and fantastic contribution. We will ensure that your pull request is a successful and pleasant experience.

Your suggestions for changes to the GOA TOOLs open source project are excellent as they are well defined, tight, and will not break anything for so many users.

I liked this step-by-step guide (https://www.dataschool.io/how-to-contribute-on-github/) to contributing to open source projects because it describes the "why" behind each command and how to work with the three repositories in a pull request:
  * **upstream remote**: Our copy on GitHub: https://github.com/tanghaibao/goatools
  * **origin remote**: Your forked copy on GitHub: https://github.com/yotamcons/goatools
  * **local repository**: Your cloned copy on your local disk

You can find other guides by searching for:
 *  "how to contribute on github"
 *  "how to contribute to github as a beginner"

Congratulations on taking great first step into the open-source community!

**Comment by yotamcons** [comment]
I gave it a go, would love to get feedback:
[https://github.com/tanghaibao/goatools/pull/236](https://github.com/tanghaibao/goatools/pull/236)

**Comment by tanghaibao** [comment]
@yotamcons 

Thank you for your contribution! We'll merge it in.

Haibao
