### ISSUE TITLE
Purification with zero results

### ISSUE THREAD

**Issue by shelkmike** [tanghaibao/goatools#41]
Hi all!

If I understand correctly, if in a first sample of comparison some GO is abscent and in the other - is present abundantly, goatools will not count it as a purification and will not print in results at all. While, as I think, it should be counted as a strong purification. Was it made intentionally or is it a bug?

**Comment by tanghaibao** [comment]
@shelkmike,

Thanks for reporting this issue. This is indeed a bug. GOATOOLS was initially designed to discover enriched terms so only terms present in the 'study' were tested. One potential problem, as I noted in my commit message, is that since we are now testing essentially every single term present in both 'study' and 'population', this significantly increases the number of tests we performed and therefore the p-values after multiple testing correction are now numerically different from before. I'll sit on this a bit longer before updating the PyPI package.

Haibao
