### ISSUE TITLE
Loci with no GO annotation

### ISSUE THREAD

**Issue by AGrusz** [tanghaibao/goatools#45]
Hi there, 

I am using goatools to test for over- and/or under-represented GOSlim categories in a plant lineage that is lacking a closely-related annotated genome. Thus, for the 2091 loci in my "population" only 819 have known GO annotations. Similarly, my "study" data sets have many loci that are also lacking GO annotations. 

My question is: Should I include loci in my "population" and "study" files that do not have GO annotations? I am concerned that, if I only use loci for which there are annotations, I may bias the results.

Any suggestions/input would be much appreciated.

Thanks!

**Comment by dvklopfenstein** [comment]
Hello,

There are some conflicting advice.  I tried both and went with the advice at #1:

#1) http://geneontology.org/page/go-enrichment-analysis
_Background frequency_ is the number of genes annotated to a GO term in the entire background set, while _sample frequency_ is the number of genes annotated to that GO term in the input list. For example, if the input list contains 10 genes and the enrichment is done for biological process in S. cerevisiae whose background set contains 6442 genes, then if 5 out of the 10 input genes are annotated to the GO term: DNA repair, then the sample frequency for DNA repair will be 5/10. Whereas if there are 100 genes annotated to DNA repair in all of the S. cerevisiae genome, then the background frequency will be 100/6442.

#2) Is to use:
fisher(
  Study genes In anno group(5 in example above),
  Study genes Not in anno group(5 in example above),
  Population genes In anno group(100 in example above).
  Population genes Not in anno group(6342 in example above)

I chose to go with #1 because the info appeared on the geneontology website and my results on my data looked reasonable.

I do not do any compensation for genes that are not annotated. But I am doing GO analysis on Human protein-coding genes, which are well annotated.

If I were in your shoes, I would try #1, #2, and then repeat #1 & #2, but excluding any un-annotated genes from both the study group and the population group.  See which analysis produces the most sensible results and then use that.
