### ISSUE TITLE
Unable to install on Windows

### ISSUE THREAD

**Issue by deto** [tanghaibao/goatools#60]
Not really an issue with goatools, but I thought I'd put this here to draw attention to this issue:

https://github.com/brentp/fishers_exact_test/issues/16

... which was preventing me from installing fisher (and as a result, goatools) in Windows.

Although I believe I have identified the problem, I'm not versed enough in C/Cython to submit a fix.

For anyone else having this issue, here is a temporary fix:

1. Clone the fisher repo locally and navigate to its root folder
2. Checkout commit e550127
3. Run "pip install ."  (that's pip install <dot>) to install the package
4. Now install goatools using pip install goatools

I haven't verified, though, that the fisher package at commit e550127 is stable, though, so you might run into issues doing enrichment tests.  However, I just wanted to download a parser for the obo files so this works for me.

**Comment by deto** [comment]
Alternately, it looks like scipy has the fishers exact test

http://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.fisher_exact.html#scipy.stats.fisher_exact

Switching to this wouldn't actually be adding a scipy dependency either as statsmodels (already required for goatools) already depends on scipy.

**Comment by dvklopfenstein** [comment]
Hi Deto, Yes.  I use scipy fisher_exact locally when using iPython in Windows.

Check for updates in the next couple of days... Coding is done. Tests are not (yet - almost).

Here is the plan:

Just as GOATOOLs provides the user with many options for multiple test correction, it is beneficial to also provide the user with multiple options for the statistical test to calculate the uncorrected p-values. 

Since you bring this up now, it is a good time to implement this added flexibility. The new code is written and running, but tests are still in progress. Please give me a day or two and then you will have the option to use scipy stats fisher_exact test as well a the original fisher option. Adding this new infrastructure will also make it possible for other users to add their own favorite options for statistical tests to calculate uncorrected p-values.

So we will not be switching to a new statistical test. We will be adding infrastructure to support a user-specified statistical test from many (beginning with two) options. Users can add new statistical tests in this infrastructure, if they wish.

**Comment by deto** [comment]
Thanks for your quick responses in fixing the situation.

Is the fisher module still going to be listed as a dependency of the project, though?  This will prevent users on Windows from installing - at least until that project fixes the current issue.

**Comment by dvklopfenstein** [comment]
I'll take "fisher" out of the required packages since "fisher" will be one one of a hopefully many interesting future options that people might think to add.

**Comment by dvklopfenstein** [comment]
Everything is checked in. You now have the option of using calculating uncorrected pvalues using either the "fisher" package or scipy stat's fisher_exact function.

Please give it a try. If there are any issues, please let us know.

Thank you very much for using GOATOOLs and for your helpful feedback.

DV

**Comment by deto** [comment]
Your solution looks great - how your abstracted out the fisher function.

One thing I noticed that might trip people up, though:  Even though removing fisher from the requirements was necessary to allow for install on Windows, choosing fisher to be the default (and not scipy fisher) will end up causing errors for users who install this and give it a try, not knowing that they need to set the fisher option to scipy or install the fisher library.

One way to fix this would be to set the default to some sentinel value, like "unspecified", and then in the code check if you can import fisher (wrap the import statement in a try, except "importerror") and if not, set the value to the scipy option.

**Comment by dvklopfenstein** [comment]
That is a good idea.

We prefer to keep fisher as the default because that is what most people
are currently using, so keeping it as the default involves no change for
the people currently using GOATOOLs.

The new default behavior will be to try fisher first, if it
fails(silently), then we will try scipy stats' fisher. If both fail, then
we will print out the error messages for both. If scipy works, we will
print no errors and in stdout specify which one we are using.

Thank you for your good ideas. Thank you for using GOATOOLs.

**Comment by dvklopfenstein** [comment]
Do you want to code this? Please do, if you want to.

**Comment by deto** [comment]
Sure, see my PR #63
