### ISSUE TITLE
Unable to compute similarity between most of entities

### ISSUE THREAD

**Issue by MuhammadZeeshan34** [tanghaibao/goatools#86]
I was trying to compute similarity between two given entities. `semantic_similarity` & `resnik_sim` works for few entities but it's giving an error ` return max(common_parent_go_ids(terms, go), key=lambda t: go[t].depth) ValueError: max() arg is an empty sequence` 
It issues this error when these is no common parent in both provided entities/genes. Here is one example producing this error 
`semantic_similarity(GO:0003676, GO:0007516, go)` 

Is there any alternative to compute similarity measure between such entities who doesn't share common parents. I'm sorry If I have missed something.

**Comment by dvklopfenstein** [comment]
I changed the code so that by default, semantic_distance returns **None** if two GO IDs are on different branches, like _biological_process_ and _molecular_process_ as in your example. Please pull the latest code and see what you think.

```
>>> godag = GODag('go-basic.obo')
>>> go_mf = 'GO:0003676' # level-03 depth-03 nucleic acid binding [molecular_function]
>>> go_bp = 'GO:0007516' # level-04 depth-05 hemocyte development [biological_process]
>>> sim_d = semantic_distance(go_mf, go_bp, godag)
None
```

Or you can override the default behavior and assign a distance between two branches like this:
```
>>> sim_d = semantic_distance(go_mf, go_bp, godag, branch_dist=2) # 10 = 3 + 5 + 2
10
```

The latest GO DAG has 17 depths for the _biological_process_ branch, so that may factor into your decision about how large to make the distance (_branch_dist_) between the top of _biological_process_ and _molecular_process_:

```
>>> from goatools.rpt_lev_depth import prt_lev_depth
>>> prt_lev_depth(godag)

go-basic.obo: fmt(1.2) rel(2017-07-21) 48,990 GO Terms
Dep <-Depth Counts->  <-Level Counts->
Lev   BP    MF    CC    BP    MF    CC
--- ----  ----  ----  ----  ----  ----
00     1     1     1     1     1     1
01    24    20    22    24    20    22
02   140   137   197   262   164   369
03  1033   509   540  2027   760  1265
04  2107  1530   657  4691  1878  1448
05  3586  4696  1026  7210  4913   688
06  4549  1828   809  7284  1946   248
07  4806  1029   572  5060   900    65
08  4258   578   240  2100   362     9
09  3649   308    46   732   119     0
10  2557   170     4   195    42     0
11  1585   171     1    47    22     0
12   917    68     0     1     0     0
13   322    55     0     0     0     0
14    71    17     0     0     0     0
15    21     9     0     0     0     0
16     8     1     0     0     0     0
```

**Comment by dvklopfenstein** [comment]
Thank you for your interest in GOATOOLS and time to report this issue. We have modified the software so that you should no longer see the error that you reported and added an additional related option which might be helpful to you semantic_distance. Please feel free to reopen an issue if the changes have not met your needs or you have a new item. Thank you again for your time and interest in GOATOOLS.
