### ISSUE TITLE
get_assc_pruned, but for a minimum number of genes

### ISSUE THREAD

**Issue by Melnorme1984** [tanghaibao/goatools#93]
Your library has a function called `get_assc_pruned` that, given an association between genes and GO terms, removes all the GO terms that have more than a given number (`max_genecnt`) of associated genes.

How about adding a `min_genecnt` parameter for removing those GO terms that have _less_ than that number of associated genes? My application needs both.

**Comment by dvklopfenstein** [comment]
Melnorme1984,

Thank you for your interest in GOATOOLS and for contacting us regarding adding the new argument to get_assc_pruned.

I have made the changes and added a test for the new functionality. Please do a pull request to get the new functionality. It will not yet be available from PyPi because we still need to update the GOATOOLS version.

Other researchers will surely benefit from your good suggestion. Thank you again for using GOATOOLS.

**Comment by dvklopfenstein** [comment]
I am going to close this issue as the code has been added. Please open a new issue if you need modifications.

Thank you for taking the time to offer your ideas for GOATOOLS. They are quite helpful.
