### ISSUE TITLE
Difficulties loading GO obo files using GoSearch

### ISSUE THREAD

**Issue by vruano** [tanghaibao/goatools#98]
It seems that the latest (pip installable) goatools on the lastest (fresh from GO.org) obo don't like to work with each other.

If I try go-basic.obo it tells me that the GO Dag is basically empty (no terms , no relationships). If I try go.obo it results in a recursion stack overflow.

I'm using it in python 3.6.4 if that may have any effect.

Thanks for taking a look.

Here is the code to reproduce:

```python
import goatools as goa
from goa.go_search import GoSearch
import urllib.request as ur
ur.urlretrieve("http://purl.obolibrary.org/obo/go.obo", 'go.obo')
ur.urlretrieve("http://purl.obolibrary.org/obo/go-basic.obo", 'go-basic.obo')
print(goa.__version__)
```
0.8.4
```python
go_search = GoSearch('go-basic.obo',dict())
```
go-basic.obo: fmt(None) rel(None) 0 GO Terms; optional_attrs(comment def relationship synonym xref)
```python
go_search = GoSearch('go.obo',dict())
```
...
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/goatools/obo_parser.py in _init_reldepth(rec)
    384                 up_terms = rec.get_goterms_upper()
    385                 if up_terms:
--> 386                     rec.reldepth = max(_init_reldepth(rec) for rec in up_terms) + 1
    387                 else:
    388                     rec.reldepth = 0

RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by dvklopfenstein** [comment]
vruano,

Thank you for your interest in GOATOOLS and taking the time to write to us.

When you do this 'ls' command, what do you see? Do you see the following?:

```
ls -rlth *.obo
-rw-r--r--+ 1 note2 note2 35M May  3 21:45 go.obo
-rw-r--r--+ 1 note2 note2 33M May  7 15:10 go-basic.obo
```

GOATOOLS requires the acyclic version of the go and so requires the information in go-basic.obo. 
go.obo will definitely not work and you will see this fatal error if you try to use go.obo:

```
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

**Comment by dvklopfenstein** [comment]
Can you provide a test which reproduces the error? 

I am not able to reproduce your error with this new test which uses the go-basic.obo:
```
$ tests/test_gosearch_emptydict.py
go-basic.obo: fmt(1.2) rel(2018-05-03) 47,215 GO Terms; optional_attrs(comment def relationship synonym xref)
```

**Comment by dvklopfenstein** [comment]
Could you try running the new test, tests/test_gosearch_emptydict.py, and copy the messages printed to the screen?

**Comment by dvklopfenstein** [comment]
I am going to close this issue for now since tests/test_gosearch_emptydict.py shows how to run with GoSearch without the error. 

It may be that there is some error in usage resulting in an error message which should be more helpful. We would like to improve the error message if this is the case and correct the error if it is a GOATOOLS error. But currently, we are not able to reproduce this error. If you have a test which reproduces this error, please re-open this issue and we will either correct the error or provide a more informative error message if it may be a usage issue.

Thank you for your interest in GOATOOLS and taking the time to write us. I wish the resolution could be more satisfying. Please do re-open if you can help us reproduce the error.
